// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSetpointChange();
void onStatusChange();

float humidity;
float setpoint;
float temperature;
bool alarm;
bool status;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(setpoint, READWRITE, ON_CHANGE, onSetpointChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(status, READWRITE, ON_CHANGE, onStatusChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
